# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 11:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BuiltPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 7, 4, 11, 27, 39, 68245))),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='bundle_content',
            field=models.ManyToManyField(to='versiontracker.Package'),
        ),
        migrations.AddField(
            model_name='builtpackage',
            name='package_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versiontracker.Package'),
        ),
        migrations.AddField(
            model_name='builtpackage',
            name='requested_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='builtbundle',
            name='bundle_list',
            field=models.ManyToManyField(to='versiontracker.BuiltPackage'),
        ),
    ]
