# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 11:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versiontracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtpackage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 11, 30, 52, 99127)),
        ),
        migrations.AlterField(
            model_name='builtpackage',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
